### ISSUE TITLE
As a Windows user...

### ISSUE THREAD

**Issue by Nekofirefire** [suppertails66/madou1mdtools#1]
I would like to have the madou1en.md file but, because build.sh is executable only with bash and that it's very complicate to install it on Windows can you tell me how should i do (or maybe just upload it) ? 
Have a nice day  ! (sorry for my bad english i'm french)

**Comment by suppertails66** [comment]
I sympathize, but the truth is, I haven't used Windows in years and really, really don't want to anymore. Even if I did, porting the build script to the Windows shell would take time and effort that I'd rather spend on other things. Sorry, but it's just not something I can do at this point! I know it's complicated, but if you don't want to use Linux, figuring out how to get bash working on Windows is probably your best bet. Unfortunately, I don't know anything about how to do that.
